import React from 'react'

const Home = () => {
  return (
    <div className="main-content" >
      {/* <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p>
      <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis nihil accusantium et nulla nisi tenetur? Voluptatem deleniti culpa sed, facilis iste eaque libero reprehenderit repudiandae quas vitae cupiditate quibusdam obcaecati autem eum a excepturi voluptas pariatur soluta quam optio minima alias quae? Expedita, et architecto iusto a ipsum inventore voluptatem, aperiam impedit quis ducimus beatae odit, aspernatur assumenda! Sint totam, laudantium error porro sit tenetur illo minus maxime, aspernatur asperiores magnam sed tempore excepturi distinctio a iusto quam. Nesciunt quae itaque nostrum minus. Ipsa, placeat? Provident placeat perspiciatis fugit, id expedita dolorem pariatur modi. Sint exercitationem dolores nulla ducimus aperiam?</p> */}
      <h1 className='text-4xl font-semibold'> Home </h1>
    </div>
  )
}

export default Home